server:
  # to disable SSL redirection. As our ingress controller handles this
  extraArgs:
    - --insecure
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.org/hsts: "false"
      cert-manager.io/cluster-issuer: issuer
      # This is to only allow certain IP addresses into the application: but its not working so look into it
      # nginx.ingress.kubernetes.io/whitelist-source-range: 86.171.212.33, 31.14.250.41

    hosts:
    - argocd.lab.mohammedsayed.com
    tls:
    - secretName: argocd-ingress-tls
      hosts:
      - argocd.lab.mohammedsayed.com

global:
  domain: argocd.lab.mohammedsayed.com